# Generated by Django 4.1.5 on 2023-04-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='my_location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
